version: '2'
services:
  dataservices:
    build: ./data_services/.
    volumes:
      - ./data_services:/usr/src/app/
    depends_on:
      - postgresql
    volumes_from:
      - postgresql
    links:
      - postgresql 
    ports:
      - "8000:8000"
    env_file: ./data_services/.env
    command: python main.py 
  postgresql:
    build: ./postgresql/.
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    restart: always
    build: .
    depends_on:
      - dataservices
    volumes:
      - ./services:/usr/src/app/services
      - ./stylesheets:/usr/src/app/stylesheets
      - ./server:/usr/src/app/server/
      - ./scripts:/usr/src/app/scripts
      - ./view:/usr/src/app/view
      - ./icons:/usr/src/app/icons
      - ./logos:/usr/src/app/logos
      - ./data:/usr/src/app/data

    links:
      - postgresql:postgresql
    ports:
      - "8080:8080"
    env_file: .env
  nginxproxy:
    restart: always
    build: ./nginxproxy/
    ports:
      - "80:80"
    volumes:
      - /www/static
      - /www/media
    volumes_from:
      - web
    links:
      - web
    depends_on:
      - web